# Generated by Django 4.2.9 on 2024-02-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_premium_user',
        ),
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.IntegerField(default=0),
        ),
    ]
