# Generated by Django 4.2.9 on 2024-02-01 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_premium'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_premium',
            new_name='is_premium_user',
        ),
    ]
