# Generated by Django 5.0.1 on 2024-01-21 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artist", "0003_remove_artist_music"),
        ("music", "0003_music_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="music",
            name="artist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="music",
                to="artist.artist",
            ),
        ),
    ]
