# Generated by Django 5.0.1 on 2024-01-22 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0005_remove_music_artist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaylistSong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_title", models.CharField(max_length=200)),
                ("song_youtube_id", models.CharField(max_length=20)),
                ("song_albums", models.CharField(max_length=255)),
                ("song_dur", models.CharField(max_length=7)),
                ("song_channel", models.CharField(max_length=100)),
                ("song_date_added", models.CharField(max_length=12)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
