# Generated by Django 5.0.1 on 2024-01-23 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0006_playlistsong"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="music",
            options={"ordering": ["-created_at"]},
        ),
    ]
