# Generated by Django 5.0.1 on 2024-01-24 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0007_alter_music_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="music.category"
                    ),
                ),
                (
                    "music",
                    models.ManyToManyField(
                        related_name="album_music", to="music.music"
                    ),
                ),
            ],
        ),
    ]
