# Generated by Django 5.0.1 on 2024-01-24 04:49

import helpers.upload_image
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0008_album"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=helpers.upload_image.upload_album_image
            ),
        ),
    ]
