# Generated by Django 5.0.1 on 2024-01-25 09:45

import helpers.upload_image
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0010_album_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlistsong",
            name="song_albums",
        ),
        migrations.RemoveField(
            model_name="playlistsong",
            name="song_channel",
        ),
        migrations.RemoveField(
            model_name="playlistsong",
            name="song_date_added",
        ),
        migrations.RemoveField(
            model_name="playlistsong",
            name="song_dur",
        ),
        migrations.RemoveField(
            model_name="playlistsong",
            name="song_title",
        ),
        migrations.RemoveField(
            model_name="playlistsong",
            name="song_youtube_id",
        ),
        migrations.AddField(
            model_name="playlistsong",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=helpers.upload_image.upload_music_cover_image,
            ),
        ),
        migrations.AddField(
            model_name="playlistsong",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=helpers.upload_image.upload_music_image
            ),
        ),
        migrations.AddField(
            model_name="playlistsong",
            name="music",
            field=models.ManyToManyField(
                related_name="playlist_music", to="music.music"
            ),
        ),
        migrations.AddField(
            model_name="playlistsong",
            name="name",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
