# Generated by Django 5.0.1 on 2024-01-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0011_remove_playlistsong_song_albums_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="music",
            name="category",
        ),
        migrations.AddField(
            model_name="music",
            name="category",
            field=models.ManyToManyField(related_name="music", to="music.category"),
        ),
    ]
