# Generated by Django 4.2.9 on 2024-02-02 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_alter_playlistsong_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistsong',
            name='cover_image',
        ),
    ]
