# Generated by Django 4.2.9 on 2024-01-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proaccountpurchase',
            name='address',
        ),
        migrations.RemoveField(
            model_name='proaccountpurchase',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='proaccountpurchase',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='proaccountpurchase',
            name='name',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='proaccountpurchase',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
