# Generated by Django 4.2.9 on 2024-01-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_proaccountpurchase_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField(max_length=255)),
                ('price', models.IntegerField()),
                ('stripe_id', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='ProAccountPurchase',
        ),
    ]
