# Generated by Django 4.2.9 on 2024-01-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_account_delete_proaccountpurchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
