# Generated by Django 4.2.9 on 2024-01-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_account_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='stripe_id',
        ),
        migrations.AddField(
            model_name='account',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
