# Generated by Django 5.0.1 on 2024-01-21 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("artist", "0002_artist_cover_image_artist_pseudonym"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artist",
            name="music",
        ),
    ]
