# Generated by Django 5.0.1 on 2024-01-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artist", "0003_remove_artist_music"),
        ("music", "0005_remove_music_artist"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="music",
            field=models.ManyToManyField(related_name="artists", to="music.music"),
        ),
    ]
