# Generated by Django 4.2.9 on 2024-01-30 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0013_alter_playlistsong_image"),
        ("artist", "0006_alter_artist_date_of_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artist",
            name="music",
        ),
        migrations.AddField(
            model_name="artist",
            name="music",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="music.music",
            ),
        ),
    ]
