# Generated by Django 4.2.9 on 2024-01-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0013_alter_playlistsong_image"),
        ("artist", "0007_remove_artist_music_artist_music"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artist",
            name="music",
        ),
        migrations.AddField(
            model_name="artist",
            name="music",
            field=models.ManyToManyField(related_name="artists", to="music.music"),
        ),
    ]
